name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   - name: WordPress Plugin Deploy
  uses: 10up/action-wordpress-plugin-deploy@1.4.0
  env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
